<?php class button extends analyse{protected $classe = __CLASS__;protected $filepath;protected $alt;static $compteur = 0;protected $type;protected $action;protected $enctype;protected $method;protected $target;protected $width;protected $height;
private $t_enctype = array( 'data'=>'multipart/form-data','url'=>'application/x-www-form-urlencoded','text'=>'text/plain' );private $t_target = array( 'blank'=>'_blank', 'self'=>'_self', 'parent'=>'_parent','top'=>'_top' );function __construct( $param=NULL ){$this::$compteur++;
$st = parent::string_array( $param );if( $st !== NULL ){$tmp = parent::format_parameter( $param, $st );parent::tri_parameter( $tmp[0] );}else{$tmp[0]= get_class_vars( $this->classe );}parent::set_name( $tmp[0]['name'] );parent::set_id( $tmp[0]['id'] );parent::set_css( $tmp[0]['css'] );parent::set_br( $tmp[0]['br'] );
parent::set_value( $tmp[0]['value'] );parent::set_form( $tmp[0]['form'] );$this->set_type( $tmp[0]['type'] );$this->set_alt( $tmp[0]['alt'] );$this->t_form_multi( $tmp[0]['action'], $tmp[0]['enctype'], $tmp[0]['method'],$tmp[0]['target'] );
if( is_file( $tmp[0]['filepath'] ) && $this->type == 'image' ){$tmp[0]['filepath'] = ltrim( $tmp[0]['filepath'], '\\' );$this->filepath = strtr( $tmp[0]['filepath'], "\\", "/");}$this->set_dimension( $tmp[0]['width'], $tmp[0]['height']);if( $this->globalattr == 1 ){
$this->globalattr = new global_attr( $tmp[0]['accesskey'],$tmp[0]['contenteditable'], $tmp[0]['contextmenu'], $tmp[0]['draggable'],$tmp[0]['hidden'], $tmp[0]['spellcheck'], $tmp[0]['tabindex'],$tmp[0]['title'], $tmp[0]['dropzone'] );}}
private function set_type( $arg=NULL ){$arg = strtolower( $arg );switch( $arg ){case 'button':$this->type = 'button';break;case 'reset':$this->type = 'reset';break;case 'image':$this->type = 'image';break;default:$this->type = 'submit';}}
private function set_alt( $arg=NULL ){if( $this->type != 'image' ){$this->alt = NULL;return;}elseif( is_string( $arg ) ){$this->alt = $arg;}else{$this->alt = 'OK';}}
function posyx(){$pos = array( 'x'=>NULL, 'y'=>NULL );if( isset( $_REQUEST[ $this->name.'_x' ] ) ){$pos['x'] = $_REQUEST[ $this->name.'_x'];}if( isset( $_REQUEST[$this->name.'_y'] ) ){$pos['y'] = $_REQUEST[$this->name.'_y'];}return $pos;}
private function t_form_multi( $action=NULL, $enctype=NULL, $methode=NULL ,$target=NULL ){$enctype = strtolower( $enctype  );$target = strtolower( $target );$method = strtolower( $methode );if( $this->type == 'submit' || $this->type == 'image' ){
if( array_key_exists( $enctype, $this->t_enctype ) ){$this->enctype = $this->t_enctype[$enctype];}else{$this->enctype = NULL;}if( array_key_exists( $target, $this->t_target ) ){$this->target = $this->t_target[$target];}else{$this->target = NULL;}if( $method == 'post' || $method == 'get' ){
$this->method = $method;}else{$this->method = NULL;}if( is_string( $action ) ){$this->action = $action;}else{$this->action = NULL;}}}
private function set_dimension( $width = NULL, $height = NULL ){if( $this->type == 'image' ){if( ctype_digit( $width ) && $width > 0  ){$this->width = $width;}else{$this->width = NULL;}if( ctype_digit( $height ) && $height > 0  ){
$this->height = $height;}else{$this->height = NULL;}if( $this->filepath == NULL ){$this->width = 80;$this->height = 48;}}}
function write( $screen = NULL ){$l1 = '<input name="'.$this->name.'" type="'.$this->type.'"';if( $this->id != NULL ){$l1 .= ' id="'.$this->id.'"';}if( $this->type == 'image' && $this->filepath != NULL ){$l1 .= ' src="'.$this->filepath.'"';}
if( $this->alt != NULL ){$l1 .= ' alt="'.$this->alt.'"';}if( isset( $this->value[0] ) ){$l1 .= ' value="'.$this->value[0].'"';}else{switch( $this->type ){case 'submit':$l1 .= ' value="OK"';break;case 'reset':$l1 .= ' value="Reset"';break;}}if( $this->css != NULL ){
$l1 .= ' '.$this->css;}if( $this->source != NULL ){$l1 .= ' '.$this->source;}if( $this->action != NULL ){$l1 .= ' formaction="'.$this->action.'"';}if( $this->enctype != NULL ){$l1 .= ' formenctype="'.$this->enctype.'"';}if( $this->method != NULL ){
$l1 .= ' formmethod="'.$this->method.'"';}if( $this->target != NULL ){$l1 .= ' formtarget="'.$this->target.'"';}if( $this->width != NULL ){$l1 .= ' width="'.$this->width.'"';}if( $this->height != NULL ){$l1 .= ' height="'.$this->height.'"';}if( $this->form != NULL ){
$l1 .= ' form="'.$this->form.'"';}if( $this->globalattr != NULL ){$l1 .= $this->globalattr->write_globalattr();}$l1 .= '>';
if( $this->br != NULL ){ $l1.= $this->br; }
if( $screen == NULL ){echo $l1, "\n";}else{echo htmlentities( $l1, ENT_QUOTES ), "\n";}}}?>